on:
  push:
    branches:
      - main
name: 🚀 Deploy production on push
jobs:
  web-deploy:
    name: 🎉 Deploy-production-serv
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 103.229.73.24
        port: 21
        username:  ${{ secrets.FTP_USERNAME_PROD }}
        password: ${{ secrets.FTP_PASSWORD_PROD }}
        exclude: |
          **/.git*
          **/.git*/**
          *.env
          *.htaccess
          **/public*
